### ISSUE TITLE
time-travel

### ISSUE THREAD

**Issue by ericmoderbacher** [sarweiler/zellen#16]
Feature addition, adding item mostly so I have an appropriate place to ask related questions.

Entails the addition of a linked list that holds the board values appended as we move through the generations.

**Comment by ericmoderbacher** [comment]
Filed first pull request. yay!

Dont close yet because I think the "automatic" seq_mode could use a counter-part "reverse-automatic"  that calls "do_the_time_warp()" instead of "generation_step()"

**Comment by sarweiler** [comment]
Thanks again for your contribution, Eric! Closing this issue now!
